### ISSUE TITLE
Issue for 1st utility script

### ISSUE THREAD

**Issue by hns-gxbank** [hnsia/dotfiles#1]
`which omz` and `which brew` command returns "omz not found" which causes test command to fail

Changing the test command to 
```
if ! which omz > /dev/null; then
  /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/HEAD/tools/install.sh)"
fi
```
works

which omz > /dev/null checks if omz can be found in the PATH. The > /dev/null part is used to suppress the output of which, as we're only interested in its exit status.

**Comment by hnsia** [comment]
Issue fixed. Closing Issue.
